name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
    - name: Install packeges
      run: sudo -H pip3 install pyTelegramBotAPI
    - name: run script
      run: python3.8 main.py  

