name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci_part:
    runs-on: ubuntu-latest


    steps:
    - name: Prepare
      id: prep  
      run: |
        DOCKER_IMAGE=alexandrandreenko/telegrambot
        VERSION=edge
        TAGS="${DOCKER_IMAGE}:${VERSION}"
        if [ "${{ github.event_name }}" = "push" ]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
        fi
        echo ::set-output name=tags::${TAGS}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_buil_latest
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.prep.outputs.tags }}

    - name: Run docker container
      run: docker run -d ${{ steps.prep.outputs.tags }}
      
    - name: Update latest image 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alexandrandreenko/telegrambot:latest
    

