name: Test for github runner
on:
  push:
    branches-ignore:
      - '**' 
  pull_request:
    branches:
      - main
    types: [merged]
  #pull_request:
  #  branches:
  #    - 'main'   

jobs:
  test_deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to test env
      if: github.ref == 'refs/heads/main'
      run: |
        cd /home/githubrunner/telgrambot
        git pull
        

