name: Test for github runner
on:
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches:
      - main
      - test2
    types: [closed]
jobs:
  test_deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to test env
      if: github.base.ref == 'main'
      run: |
        cd /home/githubrunner/telgrambot
        git pull        
        

