name: Test for github runner
on:
  push:
    branches:
      - '**' 
  pull_request:
    branches-ignore:
      - '**'   

jobs:
  test_deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to test env
      if: github.ref == 'refs/heads/test'
      run: |
        cd /home/githubrunner/telgrambot
        git pull
        bash ./testscript.sh Testapp-env

