name: Test for github runner
on:
  push:
    branches:
      - main
      - test2
  pull_request:
    branches-ignore:
      - '**'
jobs:
  test_deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to test env
      if: github.ref == 'refs/heads/main'
      run: |
        cd /home/githubrunner/telgrambot
        ./testscript.sh
        
        

