name: Test fo github runner
on:
  push:
    branches:
      - main

jobs:
  test_local_script:
    runs-on: self-hosted


    steps:
    - name: Clone repo
      uses: actions/checkout@v1
      
    - name: AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_Region }}
      
    - name: Running test script
      run: ./testscript.sh Testapp-env
