name: Test for github runner
env:
  PR_ID : "${{ github.event.pull_request.number }}"
  SRCBARANCH : "${{ github.event.pull_request.head.ref }}"
on:
  push:
    branches-ignore:
      - '**'
  pull_request:
    branches:
      - main
      - test2
    types: [closed]
jobs:
  test_deploy:
    runs-on: self-hosted
    steps:
    - name: Deploy to test env
      if: github.event.pull_request.base.ref == 'main'
      run: |
        cd /home/githubrunner/telgrambot
        ./testscript.sh ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.number }} ${{ github.event.pull_request.number }}
        

